services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - proxy-net
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - proxy-net
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
      - ./grafana/login:/var/lib/grafana
  loki:
    image: grafana/loki:latest
    container_name: loki
    networks:
      - proxy-net
    restart: unless-stopped
    ports:
      - "3100:3100"
    command: -config.file=./loki/local-config.yaml
    volumes:
      - ./loki:/etc/loki

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    networks:
      - proxy-net
    command: -config.file=./promtail/config.yml
    volumes:
      - /var/log:/var/log
      - ./promtail:/etc/promtail
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    networks:
      - proxy-net
    command:
      - --path.rootfs=/host
    ports:
      - 9100:9100
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave
volumes:
  prom_data: null
networks:
  proxy-net:
    external: true
